configuration:
  configuration_dir: "git://github.com/pyexcel/pyexcel-mobans.git!/config"
  template_dir:
    - "git://github.com/moremoban/pypi-mobans.git?submodule=true&brach=master!/statics"
    - "git://github.com/moremoban/pypi-mobans.git?submodule=true&branch=dev!/templates"
    - ".moban.d"
  configuration: yehua.yaml
targets:
  - README.rst: CUSTOM_README.rst.jj2
  - setup.py: custom_setup.py.jj2
  - requirements.txt: requirements.txt.jj2
  - "tests/requirements.txt": "tests/requirements.txt.jj2"
  - "docs/source/conf.py": "docs/source/conf.py.jj2"
  - "docs/source/index.rst": "docs/source/index.rst.jj2"
  - 'yehua/_version.py': '_version.py.jj2'
  - '.travis.yml': 'yehua_travis.yml.jj2'
  - output: CHANGELOG.rst
    configuration: changelog.yml
    template: CHANGELOG.rst.jj2
  - ".github/workflows/moban-update.yml": "moban-update.yml"
  - Makefile: Makefile.jj2
  - format.sh: format.sh.jj2
