requires:
  - type: git
    url: https://github.com/moremoban/pypi-mobans
    submodule: true
  - https://github.com/pyexcel/pyexcel-mobans
configuration:
  configuration_dir: "pyexcel-mobans:config"
  template_dir:
    - "pypi-mobans:templates"
    - ".moban.d"
  configuration: yehua.yaml
targets:
  - README.rst: CUSTOM_README.rst.jj2
  - setup.py: custom_setup.py.jj2
  - requirements.txt: requirements.txt.jj2
  - "tests/requirements.txt": "tests/requirements.txt.jj2"
  - test.sh: test.script.jj2
  - "docs/source/conf.py": "docs/source/conf.py.jj2"
  - "docs/source/index.rst": "docs/source/index.rst"
  - 'yehua/_version.py': 'version.py.jj2'
  - output: CHANGELOG.rst
    configuration: changelog.yml
    template: CHANGELOG.rst.jj2
